#!/usr/bin/env bash

set -uf -o pipefail

mkdir -p "$HOME/.config/git/"
touch "$HOME/.config/git/template"

TEMPLATE_PATH="$HOME/.config/git/template"

if [[ -e "$HOME/.git-pair-colleagues.txt" ]] ; then
	COLLEAGUES="$(cat $HOME/.git-pair-colleagues.txt)"
else
	COLLEAGUES=""
fi

TRAILERS=""

while true ; do
	pick="$(echo -e "$COLLEAGUES\n$(git shortlog -e -s | cut -f2)" | uniq | fzy)"

	if [[ "$pick" != "" ]]; then
		TRAILERS+="Co-authored-by: $pick\n"
		echo "Added co-author: $pick"
	else
		break
	fi
done

if [[ "$TRAILERS" != "" ]] ; then
	echo -e "\n" > "$TEMPLATE_PATH"
	echo -e "$TRAILERS" >> "$TEMPLATE_PATH"

    echo "Don't forget to add to your $HOME/.gitconfig
                [commit]
                verbose = true
                template = ~/.config/git/template"
	echo -e "\n🧑‍💻Pairing mode enabled. Run 'git unpair' to end session."
fi


